const mongoose = require('mongoose');

const LoadSchema = new mongoose.Schema({
    loadID: String,
    loadType: String,
    loadSubType: String,
    loadTitle: String,
    loadStatus: String,
    loadPrice: Number,
    loadPickupLocation: String,
    loadPickupDate: String,
    loadPickupTime: String,
    loadDeliveryLocation: String,
    loadDeliveryDate: String,
    loadDeliveryTime: String,
    loadDescription: String,
    loadTypeOfPackaging: String,
    loadWeight: String,
    loadCarrierConfirmation: String,
    loadLength: String,
    loadWidth: String,
    loadQoutes: Number,
    loadMilesTrip: { type: Number, default: null },
    loadPaymentStatus: String,
    loadAssignedDriverID: String,
    loadSpecifiedItem: String,
    loadMovingSize: String,
    loadNumberOfBedrooms: String,
    loadNumberOfPallets: String,
    loadDeliveredStatus: String,
    loadPickupStories: String,
    loadDeliveryStories: String,
    loadSpecialHandlingRequirements: String,
    loadIndustrySector: String,
    loadPrimaryContactName: String,
    loadMajorItems: String,
    loadSecondaryContactName: String,
    loadPickupFloor: String,
    loadDeliveryFloor: String,
    loadBusinessName: String,
    loadTypeOfBusiness: String,
    loadLiftedItemsQuantity: String,
    loadHaveFreightElevator: String,
    loadDestinationOptions: String,
    loadServiceExpressOptions: String,
    loadAreaOption: String,
    loadVehicleMake: String,
    loadVehicleYear: String,
    loadVehicleModel: String,
    loadAveragePrice: String,
    loadHeight: String,
    loadQuantity: String,
    loadOperable: Boolean,
    loadConvertible: Boolean,
    loadModified: Boolean,
    loadNumberOfItems: String,
    loadTrike: Boolean,
    loadIsCrate: String,
    loadIsPallet: String,
    loadTripStarted: String,
    loadAdditionalSelectedLoadOptions: [String],
    loadIsBox: String,
    loadImages: [String],
    isOnTrailer: Boolean,
    hasTrailerPreference: Boolean,
    loadTypeOfTrailer: String,
    loadCredentialID: String,
    loadLocationStops: [{
        stop: Number,
        locationStop: String,
        locationStopAndTime: String
    }],
    loadOriginDeliveryPreference: [String],
    shipperID: String,
}, );

module.exports = mongoose.model('Load', LoadSchema);
